# Generated by Django 5.0.6 on 2024-11-20 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vbamsapp', '0006_alter_customuser_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=50)),
                ('profile_pic', models.ImageField(upload_to='vehicles/')),
                ('username', models.CharField(max_length=50)),
                ('vehicle_register_number', models.CharField(max_length=50)),
                ('vehicle_model', models.CharField(max_length=50)),
                ('vehicle_jio_location', models.CharField(max_length=100)),
                ('vehicle_trip_id', models.CharField(max_length=50)),
                ('vehicle_manufecture', models.TextField()),
                ('vehicle_engine_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_register_number', models.CharField(max_length=100, unique=True)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_manufacturer', models.CharField(max_length=100)),
                ('vehicle_location', models.CharField(max_length=255)),
                ('vehicle_trip_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('new', 'New'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vehicle Request',
                'verbose_name_plural': 'Vehicle Requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
